# Generated by Django 3.2.12 on 2023-11-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20231124_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplay',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalGenre',
        ),
        migrations.DeleteModel(
            name='HistoricalPlay',
        ),
    ]
